namespace CSWMS.Models
{
    public class FeedabackModel
    {
        public int FeedbackId { get; set; }
        public int TicketID { get; set; }
        public int? TicketCode { get; set; }
        public string? FeedBackInfo { get; set; }
        public DateTime? WorkingDate { get; set; }
        public DateTime? PurchaseDate { get; set; }
        public int? problemId { get; set; }
        public int? ActualProblemId { get; set; }
        public string? SubProblem { get; set; }
        public string? SolvedBy { get; set; }
        public int? ItemId { get; set; }
        public int? ProductId { get; set; }
        public int? PrModelId { get; set; }
        public string? SerialNo { get; set; }
        public int? ProductQty { get; set; }
        public string? UsedSpareParts { get; set; }
        public string? Remarks { get; set; }
        public string? BillStatus { get; set; }
        public int? BillId { get; set; }
        public int? CustomerId { get; set; }
        public int? StatusId { get; set; }
        public string? SRInfo { get; set; }
        public string? SRNumber { get; set; }
        public string? SRMode { get; set; }
        public string? SRrejectCause { get; set; }
        public int DillerCode { get; set; }
        public bool? IsApproved { get; set; }
        public string? ApprovedBy { get; set; }
        public string? EntryBy { get; set; }
        public string? ModifiedBy { get; set; }
        public DateTime? EntryDate { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public string? EntryPC { get; set; }
        public string? ModifiedPC { get; set; }
        public string? AssistId1 { get; set; }
        public string? AssistId2 { get; set; }
        public int TechId1 { get; set; }
        public int TechId2 { get; set; }
        public int TechId3 { get; set; }
        public int CTypeId { get; set; }
        public int WacId { get; set; }
        public string? SrImage1 { get; set; }
        public string SrImage2 { get; set; }
        public string? PSMode { get; set; }
        public string? PSNote { get; set; }
        public int SrDepoId { get; set; }
        public int PsDepoId { get; set; }
        public string? SrApplyBy { get; set; }
        public DateTime? SrApplyDate { get; set; }
        public string? SrAppCheck { get; set; }
        public DateTime? SrAppCheckDate { get; set; }
        public string? Sr1stApv { get; set; }
        public DateTime? Sr1stApvDate { get; set; }
        public string? Sr2ndApv { get; set; }
        public DateTime? Sr2ndApvDate { get; set; }
        public string? SrFinalApv { get; set; }
        public DateTime? SrFinalApvDate { get; set; }
        public DateTime? SrNoInDate { get; set; }
        public string? Ps1stApv { get; set; }
        public string? PsFinalApv { get; set; }
        public DateTime? PsApplyDate { get; set; }
        public DateTime? Ps1stAppDate { get; set; }
        public DateTime? PsDepoRecDate { get; set; }
        public DateTime? PsServcRecDate { get; set; }
        public DateTime? PsTranToDepoDate { get; set; }
        public DateTime? PsDelFrDepo { get; set; }
        public string? PsRejCoz { get; set; }
        public bool SendCost { get; set; }
        public string? File_path { get; set; }
        public decimal PartsCost { get; set; }
        public decimal OthersCost { get; set; }
        public decimal TotalCost { get; set; }
        public decimal Discount { get; set; }
        public decimal DisValue { get; set; }
        public decimal ExtendedCost { get; set; }
        public string? DiscountCoz { get; set; }
        public string? DisRejCoz { get; set; }
        public string? CostStatus { get; set; }
        public string? DisApver { get; set; }
        public DateTime? DisApvDate { get; set; }
        public string? DmgInfo { get; set; }
        public string? DmMode { get; set; }
        public string? DmRejCause { get; set; }
        public int DmDepoId { get; set; }
        public string? DmAppBy { get; set; }
        public DateTime DmAppDate { get; set; }
        public string? Dm1stApv { get; set; }
        public DateTime? Dm1stApvDate { get; set; }
        public string? Dm2ndApv { get; set; }
        public DateTime Dm2ndApvDate { get; set; }
        public string? Dm3rdApv { get; set; }
        public DateTime Dm3rdApvDate { get; set; }
        public string? DmFinalApv { get; set; }
        public DateTime DmFinalApvDate { get; set; }
        public string? CmsrInfo { get; set; }
        public string? CmsrMode { get; set; }
        public string? CmsrRejCause { get; set; }
        public string? CmsrVoltage { get; set; }
        public decimal CmsrCurrent { get; set; }
        public decimal ScResistance { get; set; }
        public decimal McResistance { get; set; }
        public string? CmsrBarPic { get; set; }
        public string? ProdBarPic { get; set; }
        public string? CmsrSerNo { get; set; }
        public string? CmsrAppBy { get; set; }
        public DateTime CmsrAppDate { get; set; }
        public string? CmsrFinalApv { get; set; }
        public DateTime CmsrFinalApvDate { get; set; }
        public string? CmsrSupBrandName { get; set; }
        public string? BarcodeNo { get; set; }
        public string    CmsrFirstApv { get; set; }
        public int SubModelId { get; set; }
        public string? TransactionId { get; set; }
        public int BillAmount { get; set; }
        public DateTime CmsrFirstApvDate { get; set; }
        public string? CancelFirstApv { get; set; }
        public DateTime CancelApvdate { get; set; }
        public string? CancelFinalApv { get; set; }
        public DateTime CancelFinalApvDatetime { get; set; }
        public string? CancelReason { get; set; }

        // From Assign Table
        public string? CustomerName { get; set; }
        public string? CustomerContactNo { get; set; }
        public string? CustomerAddress { get; set; }
        public string? ProductName { get; set; }
        public int? Productamount { get; set; }=1;
    }
    public class FeedbackListForAssign
    {
        public int AssignId { get; set; }
        public int? TicketID { get; set; }
        public string? CustomerName { get; set; }
        public string? CustomerContactNo { get; set; }
        public string? CustomerAddress { get; set; }
        public string? ProductName { get; set; }
        public string? ProblemName { get; set; }
        public bool? IsAssign { get; set; }
        public bool? SendFeedback { get; set; }
        public int? StatusId { get; set; }
        public string? StatusName { get; set; }
        public int AssignZoneId { get; set; }
        public string? ZoneName { get; set; }
        public int? SupervisorId { get; set; }
        public string? SupervisorName { get; set; }
        public int? TechnicianId { get; set; }
        public string? TechnicianName { get; set; }
        public int? StaffID { get; set; }
        public DateTime? EntryDate { get; set; }
        public DateTime? AssignDate { get; set; }
        public DateTime? FinishDate { get; set; }
        public string? Remarks { get; set; }
        public string? fsp { get; set; }
    }
}
