<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Views\pages\**" />
    <Compile Remove="wwwroot\Custome JS\**" />
    <Compile Remove="wwwroot\Rotativa\wkhtmltopdf\**" />
    <Content Remove="Views\pages\**" />
    <Content Remove="wwwroot\Custome JS\**" />
    <Content Remove="wwwroot\Rotativa\wkhtmltopdf\**" />
    <EmbeddedResource Remove="Views\pages\**" />
    <EmbeddedResource Remove="wwwroot\Custome JS\**" />
    <EmbeddedResource Remove="wwwroot\Rotativa\wkhtmltopdf\**" />
    <None Remove="Views\pages\**" />
    <None Remove="wwwroot\Custome JS\**" />
    <None Remove="wwwroot\Rotativa\wkhtmltopdf\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="wwwroot\Rotativa\wkhtmltox-0.12.6-1.msvc2015-win64.exe" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.1" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.23" />
    <PackageReference Include="Oracle.ManagedDataAccess.Core" Version="23.26.0" />
    <PackageReference Include="Rotativa.AspNetCore" Version="1.4.0" />
    <PackageReference Include="System.Data.SqlClient" Version="4.9.0" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="wwwroot\Rotativa\Rotativa\wkhtmltopdf.exe">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
